version: '3'

tasks:
  default:
  generate:*:*:
    vars:
      IN: "{{index .MATCH 0}}"
      OUT: "{{index .MATCH 1}}"
    aliases: ["gen"]
    cmds:
      - protoc --go_out={{.OUT}} --go_opt=paths=source_relative --go-grpc_out={{.OUT}} --go-grpc_opt=paths=source_relative {{.IN}}