version: '3'

tasks:
  default:
  generate:*:
    vars:
      PROTONAME: "{{index .MATCH 0}}"
    aliases: ["gen"]
    cmds:
      - protoc --go_out=gen/{{.PROTONAME}} --go_opt=paths=source_relative --go-grpc_out=gen/{{.PROTONAME}} proto/{{.PROTONAME}}/{{.PROTONAME}}.proto